### ISSUE TITLE
Using HTTP Error codes in Responses

### ISSUE THREAD

**Issue by csviri** [RedHatInsights/insights-runtimes-inventory#121]
Currently service returns HTTP response with status code 200 even if there was some error during the processing, see:

https://github.com/RedHatInsights/insights-runtimes-inventory/blob/89ed21262279486df263b86c5a182cd94eaeaf98/rest/src/main/java/com/redhat/runtimes/inventory/web/DisplayInventory.java#L291-L300

In this case a better approach that would align with the standard will be just return HTTP error code. (500 in the case above).

We might implement something more aspect oriented with quarkus, see: https://stackoverflow.com/questions/60008540/quarkus-exception-handler

**Comment by kittylyst** [comment]
This isn't the way that other Insights services seem to do this - remember that there are layers of HTTP processing on top of this. Closing as WONTFIX - will add a Backlog issue to investigate in detail why other services do it the way they do. In principle, I would normally agree with you.
