### ISSUE TITLE
Setup Code Coverage Reporting

### ISSUE THREAD

**Issue by kittylyst** [RedHatInsights/insights-runtimes-inventory#55]
Add Cobertura support to Maven build

**Comment by aptmac** [comment]
Should this be Jacoco instead? I see there's already a dependency line for it: https://github.com/RedHatInsights/insights-runtimes-inventory/blob/main/pom.xml#L34

Cobertura hasn't been updated for quite some time, and still requires tools.jar which was phased out in jdk 9.

**Comment by kittylyst** [comment]
Yes, I almost certainly did mean Jacoco. I may have partially set this up and then forgotten about it. Can you check what state it's in?

**Comment by aptmac** [comment]
Sounds good. At the moment it's just the plugin version listed in the pom file, nothing is wired up at the moment. I can get that going.
