### ISSUE TITLE
Move jvm heap min attribute from EapInstance to JvmInstance

### ISSUE THREAD

**Issue by aptmac** [RedHatInsights/insights-runtimes-inventory#87]
There's a fixme in [Utils.java](https://github.com/RedHatInsights/insights-runtimes-inventory/blob/main/events/src/main/java/com/redhat/runtimes/inventory/events/Utils.java#L83) [0] for adding a heap min attribute alongside the already present heap max.

It's actually already set for [EapInstance](https://github.com/RedHatInsights/insights-runtimes-inventory/blob/main/events/src/main/java/com/redhat/runtimes/inventory/events/Utils.java#L176) [1], so it just needs to be moved accordingly.

As an aside, the TODO  also mentions that maybe more of these attributes would be better housed in JvmInstance instead of EapInstance, so reminder to take a look at these sometime down the road as well.

[0] https://github.com/RedHatInsights/insights-runtimes-inventory/blob/main/events/src/main/java/com/redhat/runtimes/inventory/events/Utils.java#L83
[1] https://github.com/RedHatInsights/insights-runtimes-inventory/blob/main/events/src/main/java/com/redhat/runtimes/inventory/events/Utils.java#L176

**Comment by kittylyst** [comment]
Closed by PR #88
